# Generated by Django 5.2.14 on 2026-08-28 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="blogs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingPricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("site_visit", "Site Visit Booking"),
                            ("shoot", "Ad Video Shoot Booking"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in INR, before GST.",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST rate applied on top of the base amount, e.g. 18.00 for 18%.",
                        max_digits=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to stop charging for this service (bookings will be blocked).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking Pricing",
                "verbose_name_plural": "Booking Pricing",
                "ordering": ["booking_type"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="SMTP server address",
                        max_length=255,
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(
                        default=587,
                        help_text="SMTP port (e.g. 587 for TLS, 465 for SSL)",
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, help_text="Use TLS connection"),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(default=False, help_text="Use SSL connection"),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SMTP Username / Email address",
                        max_length=255,
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SMTP Password / App Password",
                        max_length=255,
                    ),
                ),
                (
                    "default_from_email",
                    models.CharField(
                        default="Sreemr Homes <noreply@sreemrhomes.com>",
                        help_text="Default Sender header (e.g. Sreemr Homes <noreply@sreemrhomes.com>)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to True to use this email configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Configuration",
                "verbose_name_plural": "Email Configurations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=200)),
                ("min_area", models.CharField(max_length=50)),
                ("max_area", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("badge", models.CharField(default="New Launch", max_length=100)),
                ("bhk", models.CharField(default="2 BHK", max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                (
                    "brouchure",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="brochures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShootBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("shoot_address", models.CharField(blank=True, max_length=300)),
                ("preferred_date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00-11:00", "9:00 AM - 11:00 AM"),
                            ("11:00-13:00", "11:00 AM - 1:00 PM"),
                            ("14:00-16:00", "2:00 PM - 4:00 PM"),
                            ("16:00-18:00", "4:00 PM - 6:00 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount charged (base + GST).",
                        max_digits=10,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisitBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("community", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("property_name", models.CharField(blank=True, max_length=250)),
                ("site_address", models.CharField(blank=True, max_length=300)),
                (
                    "property_category",
                    models.CharField(
                        choices=[("flat", "Flat / Apartment"), ("villa", "Villa")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("bhk_type", models.CharField(blank=True, max_length=50)),
                ("structure", models.CharField(blank=True, max_length=50)),
                ("floor_number", models.CharField(blank=True, max_length=50)),
                ("total_floors", models.CharField(blank=True, max_length=50)),
                ("size_sqft", models.CharField(blank=True, max_length=50)),
                ("facing", models.CharField(blank=True, max_length=20)),
                ("furnishing", models.CharField(blank=True, max_length=30)),
                ("parking", models.CharField(blank=True, max_length=30)),
                ("villa_number", models.CharField(blank=True, max_length=50)),
                ("preferred_date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("11:00-13:00", "11:00 AM - 1:00 PM"),
                            ("14:00-16:00", "2:00 PM - 4:00 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount charged (base + GST).",
                        max_digits=10,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField()),
            ],
        ),
    ]
