# Generated by Django 6.0.5 on 2026-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('min_area', models.CharField(max_length=100)),
                ('max_area', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
