# Generated by Django 6.0.5 on 2026-05-08 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='max_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='min_area',
            field=models.CharField(max_length=50),
        ),
    ]
