# Generated by Django 6.0.5 on 2026-05-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocks',
            new_name='Block',
        ),
    ]
