# Generated by Django 5.2.14 on 2026-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_blocks_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge',
            field=models.CharField(default='New Launch', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='bhk',
            field=models.CharField(default='2 BHK', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='brouchure',
            field=models.FileField(blank=True, default=None, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
