"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads sreemr-home-django/.env (never committed — see .env.example) so both
# local development and production read Supabase + R2 credentials the same way.
load_dotenv(BASE_DIR / ".env")


def require_env(*names):
    """Fetches required env vars, raising one clear error listing everything missing."""
    values = {name: os.environ.get(name) for name in names}
    missing = [name for name, value in values.items() if not value]
    if missing:
        raise ImproperlyConfigured(
            f"Missing required environment variable(s): {', '.join(missing)}. "
            f"Copy .env.example to .env in sreemr-home-django/ and fill in your "
            f"Supabase and Cloudflare R2 credentials."
        )
    return values


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment — this file is committed to a public GitHub
# repo, so a literal key here would be public too. Falls back to the
# original dev key if unset so nothing breaks locally if .env is missing it.
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-f1xlbs5e@&pr3u1$&!()2ng6z+&)yyqk82gs87xmw*k$=vlk+a"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to OFF. Set DEBUG=True in your local .env for development —
# never on the real production deployment (it leaks stack traces, settings,
# and this very SECRET_KEY to anyone who triggers an error).
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["sreemrhomess.pythonanywhere.com","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database — Supabase (managed Postgres)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_URL comes from your Supabase project: Project Settings -> Database
# -> Connection string -> URI. Prefer the direct connection or the "Session
# pooler" (port 5432) over the "Transaction pooler" (port 6543) — the
# transaction pooler doesn't support the persistent connections / advisory
# locks Django's migrations rely on.
_db_env = require_env("DATABASE_URL")

DATABASES = {
    "default": dj_database_url.parse(
        _db_env["DATABASE_URL"],
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
CORS_ALLOW_ALL_ORIGINS = True

# ---------------------------------------------------------------------------
# Cloudflare R2 (S3-compatible) for media (Project/Blogs images, brochures)
# ---------------------------------------------------------------------------
# All four values come from the Cloudflare dashboard:
#   R2 -> Manage API tokens -> create a token scoped to your bucket (Object
#   Read & Write) for R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY;
#   R2 -> your bucket -> Settings -> S3 API -> Endpoint for R2_ENDPOINT_URL;
#   R2 -> your bucket -> Settings -> Public access for R2_PUBLIC_DOMAIN
#   (either the bucket's pub-xxxx.r2.dev host, or a custom domain you've
#   connected — either way, without the "https://" prefix).
#
# These are read WITHOUT require_env() on purpose: unlike the database, media
# storage isn't touched by every command (migrate, createsuperuser, shell,
# dumpdata all work fine with no R2 config at all). The friendly "which
# variable is missing" error instead comes from website.storage.R2MediaStorage,
# raised only the first time something actually tries to read/write a file.
AWS_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL")
AWS_S3_CUSTOM_DOMAIN = os.environ.get("R2_PUBLIC_DOMAIN")
AWS_S3_REGION_NAME = "auto"
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False  # public bucket: plain URLs, no signed query params

STORAGES = {
    "default": {
        "BACKEND": "website.storage.R2MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/" if AWS_S3_CUSTOM_DOMAIN else "/media/"

# Razorpay
# Read from the environment (.env locally; real env vars / WSGI config in
# production) instead of being hardcoded here — this file is committed to a
# public GitHub repo, so a literal key here would be public too. Booking
# creation will fail with a clear Razorpay auth error if these are unset;
# every other command (migrate, createsuperuser, etc.) is unaffected.
RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET")

# Booking fee (in INR) charged to reserve an ad video shoot slot.
SHOOT_BOOKING_AMOUNT_INR = 1999

# Booking fee (in INR) charged to reserve a site visit slot.
SITE_VISIT_BOOKING_AMOUNT_INR = 1000

# Email settings (default values; dynamic configuration managed via EmailConfiguration model in Django admin).
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = "Sreemr Homes <noreply@sreemrhomes.com>"


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "SREEMR HOMES Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "SREEMR HOMES",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "SREEMR HOMES",

    

   
    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-fluid elevation-0",
    "custom_css": "None",

    "welcome_sign": "Welcome to the Sreemr Homes Admin Panel",
    "copyright": "SREEMR HOMES PVT LTD",

    

    # UI Tweaks
    "show_ui_builder": False,
    "navigation_expanded": True,
    "show_sidebar": True,



    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Sreemr Homes Admin Panel",

    # Copyright on the footer
    "copyright": "SREEMR HOMES PVT LTD",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

   

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",

    # Your app models
    "website.project": "fas fa-building",
    "website.contactmessage": "fas fa-envelope-open-text",
    "website.enquiry": "fas fa-clipboard-list",
    "website.video": "fas fa-video",
    "website.block": "fas fa-th-large",
    "website.shootbooking": "fas fa-video",
    "website.sitevisitbooking": "fas fa-map-marker-alt",
    "website.bookingpricing": "fas fa-rupee-sign",
},
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
}